### ISSUE TITLE
Exception in redis when using /velocity reload

### ISSUE THREAD

**Issue by OtakuSweett** [GemstoneGG/Velocity-CTD#386] opened 2024-12-17 17:13 UTC
### Expected Behavior

Reload configuration with /velocity reload and prevent the console from being filled with redis errors

### Actual Behavior

After using /velocity reload

The console sends a connection error in redis
this does not happen before using /velocity reload

Error:

```[11:09:12 ERROR]: redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
[11:09:12 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:42)
[11:09:12 ERROR]:       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
[11:09:12 ERROR]:       at com.velocitypowered.proxy.redis.RedisManagerImpl.getPausedQueues(RedisManagerImpl.java:190)
[11:09:12 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.isPaused(ServerQueueStatus.java:406)
[11:09:12 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.tickSending(ServerQueueStatus.java:142)
[11:09:12 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:286)
[11:09:12 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[11:09:12 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[11:09:12 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[11:09:12 ERROR]: Caused by: java.util.NoSuchElementException: Pool exhausted
[11:09:12 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:320)
[11:09:12 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233)
[11:09:12 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
[11:09:12 ERROR]:       ... 8 more
[11:09:12 ERROR]: redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
[11:09:12 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:42)
[11:09:12 ERROR]:       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
[11:09:12 ERROR]:       at com.velocitypowered.proxy.redis.RedisManagerImpl.getPausedQueues(RedisManagerImpl.java:190)
[11:09:12 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.isPaused(ServerQueueStatus.java:406)
[11:09:12 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.tickSending(ServerQueueStatus.java:142)
[11:09:12 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:286)
[11:09:12 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[11:09:12 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[11:09:12 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[11:09:12 ERROR]: Caused by: java.util.NoSuchElementException: Pool exhausted
[11:09:12 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:320)
[11:09:12 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233)
[11:09:12 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
[11:09:12 ERROR]:       ... 8 more
[11:09:13 ERROR]: redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
[11:09:13 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:42)
[11:09:13 ERROR]:       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
[11:09:13 ERROR]:       at com.velocitypowered.proxy.redis.RedisManagerImpl.getPausedQueues(RedisManagerImpl.java:190)
[11:09:13 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.isPaused(ServerQueueStatus.java:406)
[11:09:13 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.tickSending(ServerQueueStatus.java:142)
[11:09:13 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:286)
[11:09:13 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[11:09:13 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[11:09:13 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[11:09:13 ERROR]: Caused by: java.util.NoSuchElementException: Pool exhausted
[11:09:13 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:320)
[11:09:13 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233)
[11:09:13 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
[11:09:13 ERROR]:       ... 8 more
[11:09:13 ERROR]: redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
[11:09:13 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:42)
[11:09:13 ERROR]:       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
[11:09:13 ERROR]:       at com.velocitypowered.proxy.redis.RedisManagerImpl.getPausedQueues(RedisManagerImpl.java:190)
[11:09:13 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.isPaused(ServerQueueStatus.java:406)
[11:09:13 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.tickSending(ServerQueueStatus.java:142)
[11:09:13 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:286)
[11:09:13 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[11:09:13 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[11:09:13 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[11:09:13 ERROR]: Caused by: java.util.NoSuchElementException: Pool exhausted
[11:09:13 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:320)
[11:09:13 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233)
[11:09:13 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
[11:09:13 ERROR]:       ... 8 more
[11:09:14 ERROR]: redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
[11:09:14 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:42)
[11:09:14 ERROR]:       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
[11:09:14 ERROR]:       at com.velocitypowered.proxy.redis.RedisManagerImpl.getPausedQueues(RedisManagerImpl.java:190)
[11:09:14 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.isPaused(ServerQueueStatus.java:406)
[11:09:14 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.tickSending(ServerQueueStatus.java:142)
[11:09:14 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:286)
[11:09:14 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[11:09:14 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[11:09:14 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[11:09:14 ERROR]: Caused by: java.util.NoSuchElementException: Pool exhausted
[11:09:14 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:320)
[11:09:14 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233)
[11:09:14 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
[11:09:14 ERROR]:       ... 8 more
[11:09:14 ERROR]: redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
[11:09:14 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:42)
[11:09:14 ERROR]:       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
[11:09:14 ERROR]:       at com.velocitypowered.proxy.redis.RedisManagerImpl.getPausedQueues(RedisManagerImpl.java:190)
[11:09:14 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.isPaused(ServerQueueStatus.java:406)
[11:09:14 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.tickSending(ServerQueueStatus.java:142)
[11:09:14 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:286)
[11:09:14 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[11:09:14 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[11:09:14 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[11:09:14 ERROR]: Caused by: java.util.NoSuchElementException: Pool exhausted
[11:09:14 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:320)
[11:09:14 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233)
[11:09:14 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
[11:09:14 ERROR]:       ... 8 more```

### Steps to Reproduce

Step 1: Run the command /velocity reload

Step 2:  enjoy your buggy console

### Plugin List

 Plugins: velocity, easycommandblocker, floodgate, geyser, litebans, luckperms, maintenance, nlogin, skinsrestorer, spark, v4guard-plugin

### Velocity Version

velocity info
[11:13:26 INFO]: Velocity 3.4.0-SNAPSHOT (git-f6524419)
[11:13:26 INFO]: Copyright 2018-2024 Velocity Contributors. Velocity está licenciado bajo los términos de la Licencia Pública General de GNU v3.
[11:13:26 INFO]: discord.gg/beer - GitHub

### Additional Information

_No response_

**Comment by R00tB33rMan** [comment] 2024-12-17 19:15
> ### Expected Behavior
> Reload configuration with /velocity reload and prevent the console from being filled with redis errors
> 
> ### Actual Behavior
> After using /velocity reload
> 
> The console sends a connection error in redis this does not happen before using /velocity reload
> 
> Error:
> 
> ```
> [11:09:12 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:42)
> [11:09:12 ERROR]:       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
> [11:09:12 ERROR]:       at com.velocitypowered.proxy.redis.RedisManagerImpl.getPausedQueues(RedisManagerImpl.java:190)
> [11:09:12 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.isPaused(ServerQueueStatus.java:406)
> [11:09:12 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.tickSending(ServerQueueStatus.java:142)
> [11:09:12 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:286)
> [11:09:12 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> [11:09:12 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> [11:09:12 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
> [11:09:12 ERROR]: Caused by: java.util.NoSuchElementException: Pool exhausted
> [11:09:12 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:320)
> [11:09:12 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233)
> [11:09:12 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
> [11:09:12 ERROR]:       ... 8 more
> [11:09:12 ERROR]: redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
> [11:09:12 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:42)
> [11:09:12 ERROR]:       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
> [11:09:12 ERROR]:       at com.velocitypowered.proxy.redis.RedisManagerImpl.getPausedQueues(RedisManagerImpl.java:190)
> [11:09:12 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.isPaused(ServerQueueStatus.java:406)
> [11:09:12 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.tickSending(ServerQueueStatus.java:142)
> [11:09:12 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:286)
> [11:09:12 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> [11:09:12 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> [11:09:12 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
> [11:09:12 ERROR]: Caused by: java.util.NoSuchElementException: Pool exhausted
> [11:09:12 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:320)
> [11:09:12 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233)
> [11:09:12 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
> [11:09:12 ERROR]:       ... 8 more
> [11:09:13 ERROR]: redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
> [11:09:13 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:42)
> [11:09:13 ERROR]:       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
> [11:09:13 ERROR]:       at com.velocitypowered.proxy.redis.RedisManagerImpl.getPausedQueues(RedisManagerImpl.java:190)
> [11:09:13 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.isPaused(ServerQueueStatus.java:406)
> [11:09:13 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.tickSending(ServerQueueStatus.java:142)
> [11:09:13 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:286)
> [11:09:13 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> [11:09:13 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> [11:09:13 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
> [11:09:13 ERROR]: Caused by: java.util.NoSuchElementException: Pool exhausted
> [11:09:13 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:320)
> [11:09:13 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233)
> [11:09:13 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
> [11:09:13 ERROR]:       ... 8 more
> [11:09:13 ERROR]: redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
> [11:09:13 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:42)
> [11:09:13 ERROR]:       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
> [11:09:13 ERROR]:       at com.velocitypowered.proxy.redis.RedisManagerImpl.getPausedQueues(RedisManagerImpl.java:190)
> [11:09:13 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.isPaused(ServerQueueStatus.java:406)
> [11:09:13 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.tickSending(ServerQueueStatus.java:142)
> [11:09:13 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:286)
> [11:09:13 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> [11:09:13 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> [11:09:13 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
> [11:09:13 ERROR]: Caused by: java.util.NoSuchElementException: Pool exhausted
> [11:09:13 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:320)
> [11:09:13 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233)
> [11:09:13 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
> [11:09:13 ERROR]:       ... 8 more
> [11:09:14 ERROR]: redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
> [11:09:14 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:42)
> [11:09:14 ERROR]:       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
> [11:09:14 ERROR]:       at com.velocitypowered.proxy.redis.RedisManagerImpl.getPausedQueues(RedisManagerImpl.java:190)
> [11:09:14 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.isPaused(ServerQueueStatus.java:406)
> [11:09:14 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.tickSending(ServerQueueStatus.java:142)
> [11:09:14 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:286)
> [11:09:14 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> [11:09:14 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> [11:09:14 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
> [11:09:14 ERROR]: Caused by: java.util.NoSuchElementException: Pool exhausted
> [11:09:14 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:320)
> [11:09:14 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233)
> [11:09:14 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
> [11:09:14 ERROR]:       ... 8 more
> [11:09:14 ERROR]: redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
> [11:09:14 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:42)
> [11:09:14 ERROR]:       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
> [11:09:14 ERROR]:       at com.velocitypowered.proxy.redis.RedisManagerImpl.getPausedQueues(RedisManagerImpl.java:190)
> [11:09:14 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.isPaused(ServerQueueStatus.java:406)
> [11:09:14 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.tickSending(ServerQueueStatus.java:142)
> [11:09:14 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:286)
> [11:09:14 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> [11:09:14 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> [11:09:14 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
> [11:09:14 ERROR]: Caused by: java.util.NoSuchElementException: Pool exhausted
> [11:09:14 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:320)
> [11:09:14 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233)
> [11:09:14 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
> [11:09:14 ERROR]:       ... 8 more```
> 
> ### Steps to Reproduce
> 
> Step 1: Run the command /velocity reload
> 
> Step 2:  enjoy your buggy console
> 
> ### Plugin List
> 
>  Plugins: velocity, easycommandblocker, floodgate, geyser, litebans, luckperms, maintenance, nlogin, skinsrestorer, spark, v4guard-plugin
> 
> ### Velocity Version
> 
> velocity info
> [11:13:26 INFO]: Velocity 3.4.0-SNAPSHOT (git-f6524419)
> [11:13:26 INFO]: Copyright 2018-2024 Velocity Contributors. Velocity está licenciado bajo los términos de la Licencia Pública General de GNU v3.
> [11:13:26 INFO]: discord.gg/beer - GitHub
> 
> ### Additional Information
> 
> _No response_
> ```

Are you able to provide me your configuration?

**Comment by devnootnoot** [comment] 2024-12-17 20:05
Hey, your issue is caused by not having enough max connections in Redis. I'm assuming you still have it set to the default '10'. Change it to 50, and try again. Your issue should be resolved then. @OtakuSweett

**Comment by OtakuSweett** [comment] 2024-12-17 21:52
> Are you able to provide me your configuration?


Sure, this is my configuration, it is the same in each of the proxies, obviously changing IDs and ports

this didn't happen before


https://mclo.gs/qvIpNZE

**Comment by OtakuSweett** [comment] 2024-12-17 21:54
> Hey, your issue is caused by not having enough max connections in Redis. I'm assuming you still have it set to the default '10'. Change it to 50, and try again. Your issue should be resolved then. @OtakuSweett

I tried to do that and I keep getting the error:

```yaml
[15:53:39 ERROR]: redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
[15:53:39 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:42)
[15:53:39 ERROR]:       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
[15:53:39 ERROR]:       at com.velocitypowered.proxy.redis.RedisManagerImpl.getPausedQueues(RedisManagerImpl.java:190)
[15:53:39 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.isPaused(ServerQueueStatus.java:406)
[15:53:39 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.tickSending(ServerQueueStatus.java:142)
[15:53:39 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:286)
[15:53:39 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:53:39 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:53:39 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[15:53:39 ERROR]: Caused by: java.util.NoSuchElementException: Pool exhausted
[15:53:39 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:320)
[15:53:39 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233)
[15:53:39 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
[15:53:39 ERROR]:       ... 8 more
```

**Comment by R00tB33rMan** [comment] 2024-12-18 02:17
> > Hey, your issue is caused by not having enough max connections in Redis. I'm assuming you still have it set to the default '10'. Change it to 50, and try again. Your issue should be resolved then. @OtakuSweett
> 
> I tried to do that and I keep getting the error:
> 
> ```yaml
> [15:53:39 ERROR]: redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
> [15:53:39 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:42)
> [15:53:39 ERROR]:       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
> [15:53:39 ERROR]:       at com.velocitypowered.proxy.redis.RedisManagerImpl.getPausedQueues(RedisManagerImpl.java:190)
> [15:53:39 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.isPaused(ServerQueueStatus.java:406)
> [15:53:39 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.tickSending(ServerQueueStatus.java:142)
> [15:53:39 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:286)
> [15:53:39 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> [15:53:39 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> [15:53:39 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
> [15:53:39 ERROR]: Caused by: java.util.NoSuchElementException: Pool exhausted
> [15:53:39 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:320)
> [15:53:39 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233)
> [15:53:39 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
> [15:53:39 ERROR]:       ... 8 more
> ```

Can you create a ticket with us via our Discord for proactive discussion and communication? Should ease resolving this potential issue at better pace.

**Comment by devnootnoot** [comment] 2024-12-18 21:37
> > Hey, your issue is caused by not having enough max connections in Redis. I'm assuming you still have it set to the default '10'. Change it to 50, and try again. Your issue should be resolved then. @OtakuSweett
> 
> I tried to do that and I keep getting the error:
> 
> ```yaml
> [15:53:39 ERROR]: redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
> [15:53:39 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:42)
> [15:53:39 ERROR]:       at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
> [15:53:39 ERROR]:       at com.velocitypowered.proxy.redis.RedisManagerImpl.getPausedQueues(RedisManagerImpl.java:190)
> [15:53:39 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.isPaused(ServerQueueStatus.java:406)
> [15:53:39 ERROR]:       at com.velocitypowered.proxy.queue.ServerQueueStatus.tickSending(ServerQueueStatus.java:142)
> [15:53:39 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:286)
> [15:53:39 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> [15:53:39 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> [15:53:39 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
> [15:53:39 ERROR]: Caused by: java.util.NoSuchElementException: Pool exhausted
> [15:53:39 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:320)
> [15:53:39 ERROR]:       at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233)
> [15:53:39 ERROR]:       at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
> [15:53:39 ERROR]:       ... 8 more
> ```

how many players are you getting on when this happens?

**Comment by R00tB33rMan** [comment] 2024-12-24 03:27
I haven't gotten any additional reports about this issue. If you encounter this issue and can provide reproduction steps, we can discern what's occurring here. That said, I'm closing this issue. We can't find much of anything.

**Closed as completed by R00tB33rMan** 2024-12-24 03:27 UTC
