### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by Reelx69** [GemstoneGG/Velocity-CTD#231] opened 2024-06-11 05:40 UTC
Hey there, what is this error?
![image](https://github.com/GemstoneGG/Velocity-CTD/assets/96651565/894a14e5-e1cc-4643-8b5e-b497771754a5)

**Comment by R00tB33rMan** [comment] 2024-06-11 15:06
Hey! This is one I have yet to encounter. Did you properly regenerate your `lang` folder? I will look into resolving this issue; however, I would like some reproduction steps, just in case!

**Comment by R00tB33rMan** [comment] 2024-06-11 15:47
> Hey there, what is this error? ![image](https://private-user-images.githubusercontent.com/96651565/338450420-894a14e5-e1cc-4643-8b5e-b497771754a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjExNTMsIm5iZiI6MTcxODEyMDg1MywicGF0aCI6Ii85NjY1MTU2NS8zMzg0NTA0MjAtODk0YTE0ZTUtZTFjYy00NjQzLThiNWUtYjQ5Nzc3MTc1NGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE1NDczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyM2IwNmVhZDI4MmYyYTU5M2Q5ODM3OTI4NjBjZmM0ZGNmYzBkNDEyZmY4ZjJhOGIzMDhkNzkzMjcwYzlmMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.huYXiAYY6paxajVy35h6FWeRYs91jVE_zwzBkkuCvds)

Can you try the latest published version and see if this recurs? The iteration you're using appears to be quite old.

**Comment by Reelx69** [comment] 2024-06-11 15:56
Hey, I just deleted my old Velocity jar file and installed yours. After I hit restart, everything worked perfectly. However, I wanted to edit the messages, so I had to delete the lang file. Then, I restarted the server and this error appeared.

**Comment by Reelx69** [comment] 2024-06-11 15:56
I will try the latest build now.

**Comment by Reelx69** [comment] 2024-06-11 16:00
I think the error appears only if you delete the original Velocity lang files, delete the original Velocity jar file, upload yours, and then hit the restart button. In this case, the error will appear, but when you restart again, everything works perfectly.

**Comment by R00tB33rMan** [comment] 2024-06-12 02:42
I see. Well, I can't reproduce this under the conditions you mentioned. If you do everything adequately, the issue will likely not reappear. We'll look into this as the days pass, but it's unlikely that it's entirely valid for our codebase.

**Closed as completed by R00tB33rMan** 2024-06-12 02:42 UTC

**Comment by R00tB33rMan** [comment] 2024-06-17 00:28
> Hey there, what is this error? ![image](https://private-user-images.githubusercontent.com/96651565/338450420-894a14e5-e1cc-4643-8b5e-b497771754a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1ODQzNDcsIm5iZiI6MTcxODU4NDA0NywicGF0aCI6Ii85NjY1MTU2NS8zMzg0NTA0MjAtODk0YTE0ZTUtZTFjYy00NjQzLThiNWUtYjQ5Nzc3MTc1NGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDAwMjcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMzQyZWE0NDgwZDM0MGM3NWY3ZTAwMDAyMTdlNDEwNDU5NzY1ZjhjN2M0OTMwZTNmNzE2NWQ3MmQyYTg4OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LbqkUUqBxUJx4yjcHjr4Geh8DNq39PI28LXMzkcm4po)

Should be resolved in: c976390
